<?php
echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "<style>";
echo "body {";
echo "margin: 0;";
echo "padding: 0;";
echo "}";
echo "";
echo "h2, p {";
echo "margin: 10px;";
echo "}";
echo "";
echo "ul {";
echo "list-style-type: none;";
echo "margin: 0;";
echo "padding: 0;";
echo "overflow: hidden;";
echo "background-color: #333333;";
echo "}";
echo "";
echo "ul li {";
echo "float: left;";
echo "border-right:1px solid #bbbbbb;";
echo "}";
echo "";
echo "ul li:last-child {";
echo "border-right: none;";
echo "}";
echo "";
echo "ul li a {";
echo "display: block;";
echo "color: white;";
echo "text-align: center;";
echo "padding: 14px 16px;";
echo "text-decoration: none;";
echo "}";
echo "";
echo "ul li a:hover:not(.active) {";
echo "background-color: #111111;";
echo "}";
echo "";
echo "ul li a.active {";
echo "background-color: #04AA6D;";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";
echo "";
echo "<ul>";
echo "<li><a class=\"active\" href=\"Index_General.php\">Home</a></li>";
echo "<li><a href=\"Index_General.php\">General</a></li>";
echo "<li><a href=\"Index_Credits\">Credits</a></li>";
echo "<li><a href=\"Index_Configuration\">Configuration</a></li>";
echo "<li><a href=\"Index_Modules.php\">Modules</a></li>";
echo "<li><a href=\"Index_Environment\">Environment</a></li>";
echo "<li><a href=\"Index_Variables\">Variables</a></li>";
echo "<li><a href=\"Index_License.php\">Licence</a></li>";
echo "<li><a href=\"Index_All\">All</a></li>";
echo "</ul>";
echo "";
echo "</body>";
echo "</html>";
echo "";
echo "";
echo "";
?>